FallenNova.Web/Areas/Secure/Controllers/ItemDatabaseController.cs
using System.Collections.Generic;
using System.Web.Mvc;

using AutoMapper;

using FallenNova.Web.Areas.Shared.Models;
using FallenNova.Web.Areas.Secure.Models.ItemDatabaseModel;
using FallenNova.Web.Constants;
using FallenNova.Service;

namespace FallenNova.Web.Areas.Secure.Controllers
{
    [AuthenticateAndAuthorizeAttribute(Roles = Roles.Member)]
    public class ItemDatabaseController : BaseController
    {
        private const string ConstSortByName = "Name";
        private const string ConstSortByType = "Type";

        private readonly IEveOnlineService _eveOnlineService;

        public ItemDatabaseController(IEveOnlineService eveOnlineService)
        {
            _eveOnlineService = eveOnlineService;
        }

        #region Index

        //
        // GET: /secure/itemdatabase

        [HttpGet]
        public ActionResult Index(
            int pageIndex = 1, 
            int pageSize = 10,
            string sortBy = ConstSortByName,
            bool sortAscending = true,
            string keywords = null,
            bool includeItems = false,
            bool includeGalacticObjects = false)
        {
            var isKeywordsNull = (keywords == null);

            var itemDatabaseModel = new ItemDatabaseModel
            {
                Keywords = keywords,
                IncludeItems = isKeywordsNull || includeItems,
                IncludeGalacticObjects = (isKeywordsNull) || includeGalacticObjects
            };

            IPagingInfo pagingInfo = new PagingInfo
            {
                PageIndex = pageIndex,
                PageSize = pageSize,
                SortBy = sortBy,
                SortAscending = sortAscending,
                RouteName = RouteNames.Secure.Data,
                RouteUrl = RouteUrls.Secure.Data
            };

            ViewBag.ShowSearchResults = !isKeywordsNull;
            ViewBag.PagingInfo = pagingInfo;

            if (ViewBag.ShowSearchResults)
            {
                int totalResults;

                var itemDatabaseDetailsDtos =
                    _eveOnlineService.GetItems(
                    pageIndex,
                    pageSize,
                    sortBy,
                    sortAscending,
                    out totalResults,
                    keywords,
                    includeItems,
                    includeGalacticObjects);

                pagingInfo.TotalResults = totalResults;
            
                ViewBag.NameSortAscending = pagingInfo.IsSortAscending(ConstSortByName);
                ViewBag.TypeSortAscending = pagingInfo.IsSortAscending(ConstSortByType);

                Mapper.CreateMap<ItemDatabaseDetailsDto, ItemDatabaseModel.Item>();
                itemDatabaseModel.Items = Mapper.Map<IEnumerable<ItemDatabaseDetailsDto>, IEnumerable<ItemDatabaseModel.Item>>(itemDatabaseDetailsDtos);
            }

            return View(itemDatabaseModel);
        }

        #endregion

        #region Constellation

        //
        // GET: /secure/itemdatabase/constellation/117

        [HttpGet]
        public ActionResult Constellation(int id)
        {
            var constellationDetailsDto = _eveOnlineService.GetConstellationDetails(id);

            Mapper.CreateMap<ConstellationDetailsDto, ConstellationModel>();
            Mapper.CreateMap<ConstellationDetailsDto.SolarSystem, ConstellationModel.SolarSystem>();
            var constellationModel = Mapper.Map<ConstellationDetailsDto, ConstellationModel>(constellationDetailsDto);

            return View(constellationModel);
        }

        #endregion

        #region Item

        //
        // GET: /secure/itemdatabase/item/117

        [HttpGet]
        public ActionResult Item(int id)
        {
            var itemDetailsDto = _eveOnlineService.GetItemDetails(id);

            Mapper.CreateMap<ItemDetailsDto, ItemModel>();
            var itemModel = Mapper.Map<ItemDetailsDto, ItemModel>(itemDetailsDto);

            return View(itemModel);
        }

        #endregion

        #region Region

        //
        // GET: /secure/itemdatabase/region/117

        [HttpGet]
        public ActionResult Region(int id)
        {
            var regionDetailsDto = _eveOnlineService.GetRegionDetails(id);

            Mapper.CreateMap<RegionDetailsDto, RegionModel>();
            Mapper.CreateMap<RegionDetailsDto.Constellation, RegionModel.Constellation>();
            Mapper.CreateMap<RegionDetailsDto.Constellation.SolarSystem, RegionModel.Constellation.SolarSystem>();
            var regionModel = Mapper.Map<RegionDetailsDto, RegionModel>(regionDetailsDto);

            return View(regionModel);
        }

        #endregion

        #region Solar System

        //
        // GET: /secure/itemdatabase/solarsystem/117

        [HttpGet]
        public ActionResult SolarSystem(int id)
        {
            var solarSystemDetailsDto = _eveOnlineService.GetSolarSystemDetails(id);

            Mapper.CreateMap<SolarSystemDetailsDto, SolarSystemModel>();
            var solarSystemModel = Mapper.Map<SolarSystemDetailsDto, SolarSystemModel>(solarSystemDetailsDto);

            return View(solarSystemModel);
        }

        #endregion
    }
}

FallenNova.Web/Areas/Secure/Views/ItemDatabase/Constellation.cshtml
@model FallenNova.Web.Areas.Secure.Models.ItemDatabaseModel.ConstellationModel

@using FallenNova.Web.Constants

@{
    ViewBag.Title = @Model.Name;
}

@Html.Partial("_ItemDatabaseHeader")

<hgroup>
    <h3>Constellation</h3>

    <h4>@Model.Name</h4>
</hgroup>

<p>
    Constellations are collections of stars.<br />
    <br />
    Humanity finds patterns in the strangest things, and stars are no exception - not even after we have traveled into space and seen them with our bare eyes. 
    The thousands of solar systems that exist in New Eden are grouped into constellations whose members often bear the same political mark.
</p>

<p>
    Solar Systems:<br />
    
    @foreach (var item in Model.SolarSystems) 
    {
        @Html.ActionLink(item.Name, "SolarSystem", "ItemDatabase", new { id = item.Id, Area = "Secure" }, null)
        @: (Security: @item.Security.ToString(Format.Security))
        <br />
    }
    <br />

    Region: @Html.ActionLink(Model.RegionName, "Region", "ItemDatabase", new { id = Model.RegionId, Area = "Secure" }, null)
</p>

FallenNova.Web/Areas/Secure/Views/ItemDatabase/Index.cshtml
@model FallenNova.Web.Areas.Secure.Models.ItemDatabaseModel.ItemDatabaseModel

@using FallenNova.Web.Areas.Shared.Models
@using FallenNova.Web.Constants

@{
    ViewBag.Title = "Item Database";
}

@Html.Partial("_ItemDatabaseHeader")

<h3>Item Database</h3>

@using (Html.BeginRouteForm(RouteNames.Secure.Data, new { pageIndex = 1, pageSize = ViewBag.PagingInfo.PageSize, sortBy = ViewBag.PagingInfo.SortBy, sortAscending = ViewBag.PagingInfo.SortAscending }, FormMethod.Get))
{
    <fieldset>

        @Html.LabelFor(m => m.Keywords)
        @Html.TextBoxFor(m => m.Keywords, new { @class = "input-xlarge" })
       
        <label class="checkbox">
            @Html.BasicCheckBoxFor(m => m.IncludeItems) 
            @Html.LabelFor(m => m.IncludeItems)
        </label>
            
        <label class="checkbox">
            @Html.BasicCheckBoxFor(m => m.IncludeGalacticObjects) 
            @Html.LabelFor(m => m.IncludeGalacticObjects)
        </label>

    </fieldset>
    <button type="submit" class="btn btn-info"><i class="icon-search icon-white"></i> Search</button>
}

@if (ViewBag.ShowSearchResults)
{
    <h4>Search Results</h4>
    
    if (ViewBag.PagingInfo.TotalResults > 0)
    {
        @Html.Partial("_GridHeaderPartial", (PagingInfo)ViewBag.PagingInfo)
    
        <table class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th>@Html.SearchRouteLink("Name", RouteNames.Secure.Data, new { pageIndex = 1, pageSize = ViewBag.PagingInfo.PageSize, sortBy = "Name", sortAscending = ViewBag.NameSortAscending })</th>
                    <th>@Html.SearchRouteLink("Type", RouteNames.Secure.Data, new { pageIndex = 1, pageSize = ViewBag.PagingInfo.PageSize, sortBy = "Type", sortAscending = ViewBag.TypeSortAscending })</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
        
                @foreach (var item in Model.Items) 
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Type</td>
                        <td>@Html.ActionLink("View Details", item.Action, new { id = item.Id })</td>
                    </tr>
                }  

            </tbody>  
        </table>

        @Html.Partial("_GridFooterPartial", (PagingInfo)ViewBag.PagingInfo)
    }
    else
    {
        <text>No results found</text>
    }
}

FallenNova.Web/Areas/Secure/Views/ItemDatabase/Item.cshtml
@model FallenNova.Web.Areas.Secure.Models.ItemDatabaseModel.ItemModel

@{
    ViewBag.Title = @Model.Name;
}

@Html.Partial("_ItemDatabaseHeader")

<hgroup>
    <h3>Item</h3>

    <h4>@Model.Name</h4>
</hgroup>

<p>
    Name: @Model.Name<br />
    Description: @Model.Description
</p>

FallenNova.Web/Areas/Secure/Views/ItemDatabase/Region.cshtml
@model FallenNova.Web.Areas.Secure.Models.ItemDatabaseModel.RegionModel

@using FallenNova.Web.Constants

@{
    ViewBag.Title = @Model.Name;
}

@Html.Partial("_ItemDatabaseHeader")

<hgroup>
    <h3>Region</h3>

    <h4>@Model.Name</h4>
</hgroup>

<p>
    The space of New Eden is divided into political regions, the ownership of which varies from empires to pirates to nonclaimed territories. 
    The latter are often viciously fought over by capsuleers, who have all of the cunning of pirates and none of the moral restraints.
</p>

<p>
    Constellations:<br />
    
    @foreach (var item in Model.Constellations) 
    {
        <h5>@Html.ActionLink(item.Name, "Constellation", "ItemDatabase", new { id = item.Id, Area = "Secure" }, null)</h5>
        
        @: Solar Systems:<br />
        <br />
    
        foreach (var solarSystem in item.SolarSystems) 
        {
            @Html.ActionLink(solarSystem.Name, "SolarSystem", "ItemDatabase", new { id = solarSystem.Id, Area = "Secure" }, null)
            @: Security: @solarSystem.Security.ToString(Format.Security)
            <br />
        }
    }
</p>

FallenNova.Web/Areas/Secure/Views/ItemDatabase/SolarSystem.cshtml
@model FallenNova.Web.Areas.Secure.Models.ItemDatabaseModel.SolarSystemModel

@using FallenNova.Web.Constants

@{
    ViewBag.Title = @Model.Name;
}

@Html.Partial("_ItemDatabaseHeader")

<hgroup>
    <h3>Solar System</h3>

    <h4>@Model.Name</h4>
</hgroup>

<p>
    New Eden contains over five thousand known solar systems, with a glut of new ones having recently been discovered
    (discovery in this instance being defined by the ability to squeeze through both ends of a wormhole without getting killed).
</p>

<p>
    Security: @Model.Security.ToString(Format.Security)<br />
    Constellation: @Html.ActionLink(Model.ConstellationName, "Constellation", "ItemDatabase", new { id = Model.ConstellationId, Area = "Secure" }, null)<br />
    Region: @Html.ActionLink(Model.RegionName, "Region", "ItemDatabase", new { id = Model.RegionId, Area = "Secure" }, null)
</p>

FallenNova.Web/Areas/Secure/Views/ItemDatabase/_ItemDatabaseHeader.cshtml
<header>
    <div class="row">
        <div class="span12">
            <h2>
                <i class="icon-large list-alt"></i> Item Database
            </h2>
        </div>
    </div>
</header>

<hr />