FallenNova.Web/Areas/Secure/Controllers/MySpaceController.cs
using System.Collections.Generic;
using System.Web.Mvc;

using AutoMapper;

using FallenNova.Service;
using FallenNova.Web.Areas.Secure.Models.MySpaceModel;
using FallenNova.Web.Constants;
using FallenNova.Web.Controllers;

namespace FallenNova.Web.Areas.Secure.Controllers
{
    [AuthenticateAndAuthorizeAttribute(Roles = Roles.Member)]
    public class MySpaceController : BaseController
    {
        private readonly IUserService _userService;

        public MySpaceController(IUserService userService)
        {
            _userService = userService;
        }

        //
        // GET: /secure/myspace

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        #region Edit Details

        //
        // GET: /secure/myspace/editdetails

        [HttpGet]
        public ActionResult EditDetails()
        {
            var userContactDetailsDto = _userService.GetContactDetails(CurrentUser.UserId);

            Mapper.CreateMap<UserContactDetailsDto, EditDetailsModel>();
            var myDetailsModel = Mapper.Map<UserContactDetailsDto, EditDetailsModel>(userContactDetailsDto);

            return View(myDetailsModel);
        }

        //
        // POST: /secure/myspace/editdetails

        [HttpPost]
        public ActionResult EditDetails(EditDetailsModel editDetailsModel)
        {
            editDetailsModel.UserId = CurrentUser.UserId;

            if (ModelState.IsValid)
            {
                Mapper.CreateMap<EditDetailsModel, UserContactDetailsDto>();
                var userContactDetailsDto = Mapper.Map<EditDetailsModel, UserContactDetailsDto>(editDetailsModel);

                IList<string> errorMessages = new List<string>();

                if (!_userService.UpdateContactDetails(
                    userContactDetailsDto,
                    CurrentUser.UserId,
                    ref errorMessages))
                {
                    ModelState.AddModelErrors(errorMessages);
                }
                else
                {
                    return RedirectToAction("EditDetailsSuccessful");
                }
            }

            // Reaching this point means something went wrong.
            return View(editDetailsModel);
        }

        //
        // GET: /secure/myspace/editdetailssuccessful

        [HttpGet]
        public ActionResult EditDetailsSuccessful()
        {
            return View();
        }

        #endregion

        #region Edit Password

        //
        // GET: /secure/myspace/editpassword

        [HttpGet]
        public ActionResult EditPassword()
        {
            return View();
        }

        //
        // POST: /secure/myspace/editpassword

        [HttpPost]
        public ActionResult EditPassword(EditPasswordModel editPasswordModel)
        {
            editPasswordModel.UserId = CurrentUser.UserId;

            if (ModelState.IsValid)
            {
                Mapper.CreateMap<EditPasswordModel, UserPasswordDto>();
                var userPasswordDto = Mapper.Map<EditPasswordModel, UserPasswordDto>(editPasswordModel);

                IList<string> errorMessages = new List<string>();

                if (!_userService.UpdatePassword(
                    userPasswordDto,
                    CurrentUser.UserId,
                    ref errorMessages))
                {
                    ModelState.AddModelErrors(errorMessages);
                }
                else
                {
                    return RedirectToAction("EditPasswordSuccessful");
                }
            }

            // Reaching this point means something went wrong.
            return View(editPasswordModel);
        }

        //
        // GET: /secure/myspace/editpasswordsuccessful

        [HttpGet]
        public ActionResult EditPasswordSuccessful()
        {
            return View();
        }

        #endregion
    }
}

FallenNova.Web/Areas/Secure/Views/MySpace/EditDetails.cshtml
@model FallenNova.Web.Areas.Secure.Models.MySpaceModel.EditDetailsModel

@{
    ViewBag.Title = "Edit Details";
}

@Html.Partial("_MySpaceHeader")

<h3>Edit Details</h3>

<p>
    <span class="label label-info">Heads up!</span> Need to correct the minor issue with updating a user and not their role. 
</p>

@Bootstrap.Validation("The update was unsuccessful. Please correct the errors listed and try again.", ViewData.ModelState)

@using (Html.BeginForm((string)ViewBag.FormAction, "MySpace")) 
{
    <div class="control-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "input-xlarge" })
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(m => m.Surname, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(m => m.Surname, new { @class = "input-xlarge" })
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(m => m.EmailAddress, new { @class = "control-label" })
        <div class="controls">
            @Html.TextBoxFor(m => m.EmailAddress, new { @class = "input-xxlarge" })
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary">Edit Details</button>
            <a href="@Url.Action("Index", "MySpace", new { Area = "Secure" })" class="btn">Cancel</a>
        </div>
    </div>
}

FallenNova.Web/Areas/Secure/Views/MySpace/EditDetailsSuccessful.cshtml
@{
    ViewBag.Title = "Edit Details Successful";
}

@Html.Partial("_MySpaceHeader")

<hgroup>
    <h3>Edit Details</h3>

    <h4>Successful</h4>
</hgroup>

<p>
    Your details were successfully updated.
</p>

Return to the @Html.ActionLink("My Space home page", "Index", "MySpace").

FallenNova.Web/Areas/Secure/Views/MySpace/EditPassword.cshtml
@model FallenNova.Web.Areas.Secure.Models.MySpaceModel.EditPasswordModel

@{
    ViewBag.Title = "Edit Password";
}

@Html.Partial("_MySpaceHeader")

<h3>Edit Password</h3>

<p>
    New passwords need to have at least 6 characters in length.
</p>

@Bootstrap.Validation("The password update was unsuccessful. Please correct the errors listed and try again.", ViewData.ModelState)

@using (Html.BeginForm((string)ViewBag.FormAction, "MySpace")) 
{
    <div class="control-group">
        @Html.LabelFor(m => m.CurrentPassword, new { @class = "control-label" })
        <div class="controls">
            @Html.PasswordFor(m => m.CurrentPassword, new { @class = "input-xlarge" })
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(m => m.NewPassword, new { @class = "control-label" })
        <div class="controls">
            @Html.PasswordFor(m => m.NewPassword, new { @class = "input-xlarge" })
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(m => m.ConfirmNewPassword, new { @class = "control-label" })
        <div class="controls">
            @Html.PasswordFor(m => m.ConfirmNewPassword, new { @class = "input-xlarge" })
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary">Edit Password</button>
            <a href="@Url.Action("Index", "MySpace", new { Area = "Secure" })" class="btn">Cancel</a>
        </div>
    </div>
}

FallenNova.Web/Areas/Secure/Views/MySpace/EditPasswordSuccessful.cshtml
@{
    ViewBag.Title = "Edit Password Successful";
}

@Html.Partial("_MySpaceHeader")

<hgroup>
    <h3>Edit Password</h3>

    <h4>Successful</h4>
</hgroup>

<p>
    Your password was successfully updated.
</p>

Return to the @Html.ActionLink("My Space home page", "Index", "MySpace").

FallenNova.Web/Areas/Secure/Views/MySpace/Index.cshtml
@{
    ViewBag.Title = "My Space";
}

@Html.Partial("_MySpaceHeader")

<h3>Skills</h3>

<button class="btn btn-info" onclick="location.href='#';"><i class="icon-refresh icon-white"></i> Refresh Skills</button>

@section Scripts
{
    <script type="text/javascript">
    //<![CDATA[

        $(document).ready(function() {
            $('#RefreshSkills').click(RefreshSkills());
        });

        function RefreshSkills() {
            // Make an ajax call then update the table of skills.
        }

    //]]>
    </script>
}  

FallenNova.Web/Areas/Secure/Views/MySpace/_MySpaceHeader.cshtml
<header>
    <div class="row">
        <div class="span6">
            <h2>
                <i class="icon-large user"></i> My Space
            </h2>
        </div>
        <div class="span6">
            <div class="btn-group pull-right">
                <button class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-tasks icon-white"></i> Options <span class="caret"></span></button>
                <ul class="dropdown-menu pull-right">
                    <li><a href="@Url.Action("EditDetails", "MySpace", new { Area = "Secure" })"><i class="icon-edit"></i> Edit My Details</a></li>
                    <li><a href="@Url.Action("EditPassword", "MySpace", new { Area = "Secure" })"><i class="icon-edit"></i> Edit My Password</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

<hr />