FallenNova.Web/Models/Shared/IPagingInfo.cs
namespace FallenNova.Web.Areas.Shared.Models
{
    public interface IPagingInfo
    {
        int PageIndex { get; set; }
        int PageSize { get; set; }
        int TotalResults { get; set; }
        string SortBy { get; set; }
        bool SortAscending { get; set; }
        string RouteName { get; set; }
        string RouteUrl { get; set; }

        int FooterPageCount { get; }
        int FooterPageEnd { get; }
        int FooterPageStart { get; }
        int PageStart { get; }
        int PageEnd { get; }
        object RouteValuesFirst { get; }
        object RouteValuesPrevious { get; }
        object RouteValuesLast { get; }
        object RouteValuesNext { get; }
        int TotalPages { get; }

        bool IsSortAscending(string sortByMatch);
    }
}

FallenNova.Web/Models/Shared/PagingInfo.cs
using FallenNova.Shared.ExtensionMethods;

namespace FallenNova.Web.Areas.Shared.Models
{
    public class PagingInfo : IPagingInfo
    {
        public const int ConstFooterPageCount = 10;

        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public int TotalResults { get; set; }
        public string SortBy { get; set; }
        public bool SortAscending { get; set; }
        public string RouteName { get; set; }
        public string RouteUrl { get; set; }

        /// <summary>
        /// The maximum number of footer paging options.
        /// </summary>
        public int FooterPageCount
        {
            get { return ConstFooterPageCount; }
        }

        /// <summary>
        /// The page end index for the footer.
        /// </summary>
        public int FooterPageEnd
        {
            get
            {
                return (FooterPageStart + FooterPageCount - 1 < TotalPages)
                    ? (FooterPageStart + FooterPageCount - 1)
                    : TotalPages;
            }
        }

        /// <summary>
        /// The page start index for the footer.
        /// </summary>
        public int FooterPageStart
        {
            get { return PageIndex - ((PageIndex - 1) % FooterPageCount); }
        }

        /// <summary>
        /// The current page's start index.
        /// </summary>
        public int PageStart
        {
            get
            {
                return (PageIndex == 1)
                    ? 1
                    : (PageIndex - 1) * PageSize + 1;
            }
        }

        /// <summary>
        /// The current page's end index.
        /// </summary>
        public int PageEnd
        {
            get
            {
                return ((PageStart + PageSize) < TotalResults) 
                    ? PageStart + PageSize - 1
                    : TotalResults;
            }
        }

        /// <summary>
        /// Route values for the "First" link.
        /// </summary>
        public object RouteValuesFirst
        {
            get
            {
                return new
                    {
                        pageIndex = 1, 
                        pageSize = PageSize, 
                        sortBy = SortBy, 
                        sortAscending = SortAscending
                    };
            }
        }

        /// <summary>
        /// Route values for the first "..." link.
        /// </summary>
        public object RouteValuesPrevious
        {
            get
            {
                return new
                    {
                        pageIndex = (FooterPageStart - 1), 
                        pageSize = PageSize, 
                        sortBy = SortBy, 
                        sortAscending = SortAscending
                    };
            }
        }

        /// <summary>
        /// Route values for the "Last" link.
        /// </summary>
        public object RouteValuesLast
        {
            get
            {
                return new
                    {
                        pageIndex = TotalPages, 
                        pageSize = PageSize, 
                        sortBy = SortBy, 
                        sortAscending = SortAscending
                    };
            }
        }

        /// <summary>
        /// Route values for the last "..." link.
        /// </summary>
        public object RouteValuesNext
        {
            get
            {
                return new
                    {
                        pageIndex = (FooterPageEnd + 1), 
                        pageSize = PageSize, 
                        sortBy = SortBy, 
                        sortAscending = SortAscending
                    };
            }
        }

        /// <summary>
        /// Total number of pages.
        /// </summary>
        public int TotalPages
        {
            get
            {
                return (TotalResults / PageSize) + 
                    ((TotalResults % PageSize > 0) 
                    ? 1 
                    : 0);
            }
        }

        /// <summary>
        /// Determines if the current sorted field should be ascending or descending.
        /// </summary>
        /// <param name="sortByMatch">Name of field to sort by.</param>
        /// <returns>True to sort ascending, false to sort descending.</returns>
        public bool IsSortAscending(string sortByMatch)
        {
            return (((!string.IsNullOrWhiteSpace(SortBy)) && (!SortBy.EqualsCaseInsensitive(sortByMatch))) || (!SortAscending)) || !SortAscending;
        }
    }
}

FallenNova.Web/Areas/Secure/Controllers/CorpController.cs
using System.Collections.Generic;
using System.Web.Mvc;

using AutoMapper;

using FallenNova.Service;
using FallenNova.Web.Constants;
using FallenNova.Web.Areas.Shared.Models;
using FallenNova.Web.Areas.Secure.Models.CorpModel;

namespace FallenNova.Web.Areas.Secure.Controllers
{
    [AuthenticateAndAuthorizeAttribute(Roles = Roles.Member)]
    public class CorpController : BaseController
    {
        private const string ConstSortByMember = "Member";
        private const string ConstSortByCorporation = "Corporation";

        private readonly ICharacterService _characterService;

        public CorpController(ICharacterService characterService)
        {
            _characterService = characterService;
        }

        #region Index

        //
        // get: /secure/corp

        [HttpGet]
        public ActionResult Index(
            int pageIndex = 1, 
            int pageSize = 10,
            string sortBy = ConstSortByMember,
            bool sortAscending = true)
        {
            int totalResults;

            var characterDetailsDtos =
                _characterService.GetCharacters(
                pageIndex, 
                pageSize, 
                sortBy,
                sortAscending,
                out totalResults);

            IPagingInfo pagingInfo = new PagingInfo
            {
                PageIndex = pageIndex,
                PageSize = pageSize,
                TotalResults = totalResults,
                SortBy = sortBy,
                SortAscending = sortAscending,
                RouteName = RouteNames.Secure.Data,
                RouteUrl = RouteUrls.Secure.Data
            };

            ViewBag.PagingInfo = pagingInfo;
            ViewBag.MemberSortAscending = pagingInfo.IsSortAscending(ConstSortByMember);
            ViewBag.CorporationSortAscending = pagingInfo.IsSortAscending(ConstSortByCorporation);

            ViewBag.IsAdministrator = CurrentUser.IsAdministrator;

            Mapper.CreateMap<CharacterDetailsDto, MembersModel>();
            var membersModels = Mapper.Map<IEnumerable<CharacterDetailsDto>, IEnumerable<MembersModel>>(characterDetailsDtos);
            
            return View(membersModels);
        }

        #endregion

        #region Add

        //
        // GET: /secure/add

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        //
        // GET: /secure/add

        [HttpPost]
        public ActionResult Add(AddMemberModel addMemberModel)
        {
            return RedirectToAction("AddSuccessful");
        }

        //
        // GET: /secure/add/successful

        [HttpGet]
        public ActionResult AddSuccessful()
        {
            return View();
        }

        #endregion

        #region Details

        //
        // GET: /secure/corp/details/117

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View();
        }

        #endregion
    }
}

FallenNova.Web/Areas/Secure/Controllers/ForumController.cs
using System.Web.Mvc;

using FallenNova.Web.Constants;

namespace FallenNova.Web.Areas.Secure.Controllers
{
    [AuthenticateAndAuthorizeAttribute(Roles = Roles.Member)]
    public class ForumController : BaseController
    {
        //
        // GET: /secure/forum/

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

FallenNova.Web/Areas/Secure/Controllers/SearchController.cs
using FallenNova.Web.Constants;
using System.Web.Mvc;

namespace FallenNova.Web.Areas.Secure.Controllers
{
    [AuthenticateAndAuthorizeAttribute(Roles = Roles.Member)]
    public class SearchController : BaseController
    {
        #region Index

        //
        // POST: /secure/search

        [HttpPost]
        public ActionResult Index()
        {
            return View();
        }

        #endregion
    }
}

FallenNova.Web/Areas/Secure/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Web.Mvc;

using AutoMapper;

using FallenNova.Service;
using FallenNova.Web.Areas.Shared.Models;
using FallenNova.Web.Areas.Secure.Models.UsersModel;
using FallenNova.Web.Constants;
using FallenNova.Web.Controllers;

namespace FallenNova.Web.Areas.Secure.Controllers
{
    [AuthenticateAndAuthorizeAttribute(Roles = Roles.Administrator)]
    public class UsersController : BaseController
    {
        private const string ConstSortByFirstName = "FirstName";
        private const string ConstSortBySurname = "Surname";

        private const int ConstDefaultRoleId = 1; // 1 = Member

        private readonly IUserService _userService;

        public UsersController(IUserService userService)
        {
            _userService = userService;
        }

        #region Index

        //
        // GET: /secure/users

        [HttpGet]
        public ActionResult Index(
            int pageIndex = 1, 
            int pageSize = 10,
            string sortBy = ConstSortByFirstName,
            bool sortAscending = true)
        {
            int totalResults;

            var userDetailsDtos =
                _userService.GetUsers(
                pageIndex, 
                pageSize, 
                sortBy,
                sortAscending,
                out totalResults);

            IPagingInfo pagingInfo = new PagingInfo
            {
                PageIndex = pageIndex,
                PageSize = pageSize,
                TotalResults = totalResults,
                SortBy = sortBy,
                SortAscending = sortAscending,
                RouteName = RouteNames.Secure.Data,
                RouteUrl = RouteUrls.Secure.Data
            };

            ViewBag.PagingInfo = pagingInfo;
            ViewBag.FirstNameSortAscending = pagingInfo.IsSortAscending(ConstSortByFirstName);
            ViewBag.SurnameSortAscending = pagingInfo.IsSortAscending(ConstSortBySurname);

            Mapper.CreateMap<UserDetailsDto, UsersModel>();
            var usersModels = Mapper.Map<IEnumerable<UserDetailsDto>, IEnumerable<UsersModel>>(userDetailsDtos);
            
            return View(usersModels);
        }

        #endregion

        #region Add

        //
        // GET: /secure/users/add

        [HttpGet]
        public ActionResult Add()
        {
            var addUsersModel = new AddUserModel
            {
                RoleId = ConstDefaultRoleId
            };

            return View(addUsersModel);
        }

        //
        // POST: /secure/users/add

        [HttpPost]
        public ActionResult Add(AddUserModel addUsersModel)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<AddUserModel, UserContactDetailsDto>();
                var userInsertDetailsDto = Mapper.Map<AddUserModel, UserContactDetailsDto>(addUsersModel);

                IList<string> errorMessages = new List<string>();

                if (!_userService.Insert(
                    userInsertDetailsDto,
                    CurrentUser.UserId,
                    ref errorMessages))
                {
                    ModelState.AddModelErrors(errorMessages);
                }
                else
                {
                    return RedirectToAction("AddSuccessful", new { id = userInsertDetailsDto.UserId });
                }
            }

            // Reaching this point means something went wrong.
            return View(addUsersModel);
        }

        //
        // GET: /secure/users/addsuccessful/117

        [HttpGet]
        public ActionResult AddSuccessful(int id)
        {
            var userDetailsDto = _userService.GetDetails(id);

            Mapper.CreateMap<UserDetailsDto, AddUserSuccessfulModel>();
            var addUserSuccessfulModel = Mapper.Map<UserDetailsDto, AddUserSuccessfulModel>(userDetailsDto);

            return View(addUserSuccessfulModel);
        }

        #endregion

        #region Details

        //
        // GET: /secure/users/details/117

        [HttpGet]
        public ActionResult Details(int id)
        {
            var userDetailsDto = _userService.GetDetails(id, true);

            Mapper.CreateMap<UserDetailsDto, UserDetailsModel>();
            Mapper.CreateMap<RoleDetailsDto, UserDetailsModel.Role>();
            Mapper.CreateMap<CharacterDetailsDto, UserDetailsModel.Character>();
            var userDetailsModel = Mapper.Map<UserDetailsDto, UserDetailsModel>(userDetailsDto);

            return View(userDetailsModel);
        }

        #endregion

        #region Edit

        //
        // GET: /secure/users/editdetails/117

        [HttpGet]
        public ActionResult EditDetails(int id)
        {
            var userContactDetailsDto = _userService.GetContactDetails(id);

            Mapper.CreateMap<UserContactDetailsDto, EditDetailsUserModel>();
            var editDetailsUserModel = Mapper.Map<UserContactDetailsDto, EditDetailsUserModel>(userContactDetailsDto);

            return View(editDetailsUserModel);
        }

        //
        // POST: /secure/users/editdetails/117

        [HttpPost]
        public ActionResult EditDetails(EditDetailsUserModel editDetailsUsersModel)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<EditDetailsUserModel, UserContactDetailsDto>();
                var userContactDetailsDto = Mapper.Map<EditDetailsUserModel, UserContactDetailsDto>(editDetailsUsersModel);

                IList<string> errorMessages = new List<string>();

                if (!_userService.UpdateContactDetails(
                    userContactDetailsDto,
                    CurrentUser.UserId,
                    ref errorMessages))
                {
                    ModelState.AddModelErrors(errorMessages);
                }
                else
                {
                    return RedirectToAction("EditSuccessful", new { id = userContactDetailsDto.UserId });
                }
            }

            // Reaching this point means something went wrong.
            return View(editDetailsUsersModel);
        }

        //
        // GET: /secure/users/editstatus/117

        [HttpGet]
        public ActionResult EditStatus(int id)
        {
            var userStatusDetailsDto = _userService.GetStatusDetails(id);

            Mapper.CreateMap<UserStatusDetailsDto, EditStatusUserModel>();
            var editStatusUserModel = Mapper.Map<UserStatusDetailsDto, EditStatusUserModel>(userStatusDetailsDto);

            return View(editStatusUserModel);
        }

        //
        // POST: /secure/users/editstatus/117

        [HttpPost]
        public ActionResult EditStatus(EditStatusUserModel editStatusUserModel)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<EditStatusUserModel, UserStatusDetailsDto>();
                var userStatusDetailsDto = Mapper.Map<EditStatusUserModel, UserStatusDetailsDto>(editStatusUserModel);

                IList<string> errorMessages = new List<string>();

                if (!_userService.UpdateStatus(
                    userStatusDetailsDto,
                    CurrentUser.UserId,
                    ref errorMessages))
                {
                    ModelState.AddModelErrors(errorMessages);
                }
                else
                {
                    return RedirectToAction("EditSuccessful", new { id = userStatusDetailsDto.UserId });
                }
            }

            // Reaching this point means something went wrong.
            return View(editStatusUserModel);
        }

        //
        // GET: /secure/users/editsuccessful/117

        [HttpGet]
        public ActionResult EditSuccessful(int id)
        {
            var userDetailsDto = _userService.GetDetails(id);

            Mapper.CreateMap<UserDetailsDto, EditUserSuccessfulModel>();
            var editUserSuccessfulModel = Mapper.Map<UserDetailsDto, EditUserSuccessfulModel>(userDetailsDto);

            return View(editUserSuccessfulModel);
        }

        #endregion
    }
}

FallenNova.Web/Views/Shared/_Footer.cshtml
@inherits System.Web.Mvc.WebViewPage

@using FallenNova.Web.HtmlHelpers

<hr>

<footer>
    <div class="pull-left">
        @Html.Copyright("Bernie Cook")  
    </div>
    
    @if (User.Identity.IsAuthenticated)
    {
        <div class="pull-right">
            <button class="btn btn-mini" rel="tooltip" title="Add/remove this page from your bookmarks." id="bookmark"><i class="icon-bookmark"></i> Bookmark</button> 
        </div>
    }
</footer>

FallenNova.Web/Views/Shared/_GridFooterPartial.cshtml
@inherits System.Web.Mvc.WebViewPage<FallenNova.Web.Areas.Shared.Models.PagingInfo>

@using FallenNova.Web.HtmlHelpers

<div class="pagination">
    <ul>

        @if (Model.TotalPages > 1)
        {
            if (@Model.PageIndex > Model.FooterPageCount)
            {
                @Html.SearchRouteLink(
                    "First", 
                    Model.RouteName, 
                    Model.RouteValuesFirst,
                    true)
       
                @Html.SearchRouteLink(
                    "...", 
                    Model.RouteName,
                    Model.RouteValuesPrevious,
                    true)
            }

            for (int page = Model.FooterPageStart; page <= Model.FooterPageEnd; page++)
            {
                if (page == Model.PageIndex)
                {
                    <li class="active"><a href="#">@page</a></li>
                }
                else  
                {
                    @Html.SearchRouteLink(
                        page.ToString(), 
                        Model.RouteName, 
                        new { pageIndex = page, pageSize = Model.PageSize, sortBy = Model.SortBy, sortAscending = Model.SortAscending },
                        true)
                }
            }

            if (@Model.FooterPageStart <= (Model.TotalPages - Model.FooterPageCount))
            { 
                @Html.SearchRouteLink(
                    "...", 
                    Model.RouteName, 
                    Model.RouteValuesNext,
                    true)
        
                @Html.SearchRouteLink(
                    "Last",
                    Model.RouteName,
                    Model.RouteValuesLast,
                    true)
            }
        }

    </ul>
</div>

FallenNova.Web/Views/Shared/_GridHeaderPartial.cshtml
@inherits System.Web.Mvc.WebViewPage<FallenNova.Web.Areas.Shared.Models.PagingInfo>

@using FallenNova.Web.Constants
@using FallenNova.Web.HtmlHelpers

Results: @Model.PageStart.ToString(Format.Integer) to @Model.PageEnd.ToString(Format.Integer) (of @Model.TotalResults.ToString(Format.Integer))
    
View:

@Html.DropDownList("pageSize", @Model)

FallenNova.Web/Views/Shared/_Header.cshtml
@inherits WebViewPage

@using System.Web.Mvc
@using System.Web.Mvc.Html

<nav>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">

                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                
                <a class="brand" href="@Url.Action("Index", "Home")" title="View the Fallen Nova homepage">Fallen Nova</a>
                          
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a href="@Url.Action("Index", "MySpace", new { Area = "Secure" })"><i class="icon-user icon-white"></i> My Space</a></li>
                        <li><a href="@Url.Action("Index", "Corp", new { Area = "Secure" })"><i class="icon-fire icon-white"></i> Corp</a></li>
                        <li><a href="@Url.Action("Index", "ItemDatabase", new { Area = "Secure" })"><i class="icon-list-alt icon-white"></i> Item Database</a></li>
                        <li><a href="@Url.Action("Index", "Forum", new { Area = "Secure" })"><i class="icon-th-list icon-white"></i> Forum</a></li>
                
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bookmark icon-white"></i> Bookmarks <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#"><i class="icon-user"></i> John Smith (Member)</a></li>
                                <li><a href="#"><i class="icon-plane"></i> Deimos (Gallente Ship)</a></li>
                                <li><a href="#"><i class="icon-book"></i> New User Policies (Forum Post)</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Options</li>
                                <li><a href="#"><i class="icon-edit"></i> Edit Bookmarks</a></li>
                            </ul>
                        </li>
                        
                        if (User.IsInRole("Administrator"))
                        {
                            <li class="dropdown">
                                <a href="@Url.Action("Index", "Administration", new { Area = "Secure" })" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-wrench icon-white"></i> Admin <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Index", "Administration", new { Area = "Secure" })"><i class="icon-briefcase"></i> Administration</a></li>
                                    <li class="divider"></li>
                                    <li><a href="@Url.Action("SkillTree", "Administration", new { Area = "Secure" })"><i class="icon-th-large"></i> Skill Tree</a></li>
                                    <li class="divider"></li>
                                    <li><a href="@Url.Action("Index", "Users", new { Area = "Secure" })"><i class="icon-user"></i> Users</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Diagnostics</li>
                                    <li><a href="@Url.Action("Ninject", "Administration", new { Area = "Secure" })"><i class="icon-link"></i> Ninject</a></li>
                                </ul>
                            </li>
                        }
                            
                        <li>@Html.ActionLink("Log off", "LogOff", "Home", new { Area = "Public" }, null)</li>
                    }
                    else
                    { 
                        <li><a href="@Url.Action("AboutUs", "Home")"><i class="icon-info-sign icon-white"></i> About Us</a></li>
                        <li><a href="@Url.Action("Join", "Home")"><i class="icon-list-alt icon-white"></i> Join</a></li>
                        <li><a href="@Url.Action("ContactUs", "Home")"><i class="icon-envelope icon-white"></i> Contact Us</a></li>
                    }

                    </ul>
                    
                    @if (User.Identity.IsAuthenticated)
                    {
                        <section id="search">
                            @using (Html.BeginForm("Index", "Search", new { Area = "Secure" }, FormMethod.Post, new { @class = "navbar-form pull-right" }))
                            {
                                <input class="span2" type="text" placeholder="Search...">
                                <button type="submit" class="btn"><i class="icon-search"></i></button>
                            }
                        </section>
                    }
                    else
                    { 
                        <section id="login">
                            @using (Html.BeginForm("Login", "Home", new { Area = "Public" }, FormMethod.Post, new { @class = "navbar-form pull-right" }))
                            {
                                @Html.AntiForgeryToken()
                                <input class="span2" type="email" name="EmailAddress" placeholder="Email">
                                <input class="span2" type="password" name="Password" placeholder="Password">
                                <button type="submit" class="btn">Login</button>
                            }
                        </section>
                    }

                </div>

            </div>
        </div>
    </div>
    
</nav>

FallenNova.Web/Views/Shared/_Icons.cshtml
@inherits System.Web.Mvc.WebViewPage

<link rel="shortcut icon" href="@Url.Content("~/Assets/Icons/favicon.ico")" />
<link rel="apple-touch-icon-precomposed" href="@Url.Content("~/Assets/Icons/apple-touch-icon-57x57-precomposed.png")" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="@Url.Content("~/Assets/Icons/apple-touch-icon-72x72-precomposed.png")" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="@Url.Content("~/Assets/Icons/apple-touch-icon-114x114-precomposed.png")" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="@Url.Content("~/Assets/Icons/apple-touch-icon-144x144-precomposed.png")" />
<link rel="apple-touch-icon-precomposed" href="@Url.Content("~/Assets/Icons/apple-touch-icon-precomposed.png")" />
<link rel="apple-touch-icon" href="@Url.Content("~/Assets/Icons/apple-touch-icon.png")" />

FallenNova.Web/Views/Shared/_Meta.cshtml
@inherits System.Web.Mvc.WebViewPage

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="Bernie Cook">